server:
    port: 9611
    servlet:
        context-path: /bard
    jetty:
        max-http-post-size: 0
spring:
    profiles:
        include: jdbc, pagehelper, mybatis, logging, redis
    datasource:
        name: mysql
        id: dataSource
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
            #监控统计拦截的filters
            filters: stat
            driver-class-name: ${jdbc.driver-class-name}
            #基本属性
            url: ${jdbc.url}
            username: ${jdbc.username}
            password: ${jdbc.password}
            #配置初始化大小/最小/最大
            initial-size: 1
            min-idle: 1
            max-active: 20
            #获取连接等待超时时间
            max-wait: 60000
            #间隔多久进行一次检测，检测需要关闭的空闲连接
            time-between-eviction-runs-millis: 60000
            #一个连接在池中最小生存的时间
            min-evictable-idle-time-millis: 300000
            validation-query: select 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
            pool-prepared-statements: false
            max-pool-prepared-statement-per-connection-size: 20
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB

controller-aspect:
    exclude-urls: #list
        - /auth/login
        - /token/valid
